/*
 * Copyright (C) 2022, HENSOLDT Cyber GmbH
 * SPDX-License-Identifier: BSD-3-Clause
 */

#pragma once

#define HARDWARE_SYSTEM_CONTROLLER_EXTRA_IMPORTS

#define HARDWARE_SYSTEM_CONTROLLER_COMPONENT

#define HARDWARE_SYSTEM_CONTROLLER_INTERFACES

#define HARDWARE_SYSTEM_CONTROLLER_EXTRA_INTERFACES

#define HARDWARE_SYSTEM_CONTROLLER_ATTRIBUTES

#define HARDWARE_SYSTEM_CONTROLLER_COMPOSITION

#define HARDWARE_SYSTEM_CONTROLLER_CONFIG